version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 4200:4200
    working_dir: /app
    volumes:
      - ./:/app

  api:
    image: python:3.7
    command: sh -c "pip3 install -r requirements.txt && python3 app.py"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./deezer-back/:/app
